# Generated by Django 5.0.1 on 2024-02-04 23:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobOrderId', models.CharField(max_length=50, unique=True)),
                ('jobOrderCreatedDate', models.DateTimeField()),
                ('jobOrderStatus', models.CharField(max_length=50)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipeId', models.CharField(max_length=50)),
                ('recipeName', models.CharField(max_length=50)),
                ('recipeProdDate', models.DateField()),
                ('recipeTimeVar', models.DurationField(max_length=50, null=True)),
                ('recipeProdRate', models.PositiveIntegerField(null=True)),
                ('recipeBatchSize', models.PositiveIntegerField(null=True)),
                ('recipeTotalSales', models.PositiveIntegerField(null=True)),
                ('recipeBatches', models.PositiveIntegerField(null=True)),
                ('recipeStdTime', models.DurationField(null=True)),
                ('recipeCycleTime', models.DurationField(null=True)),
                ('recipeWaste', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('recipeSpongeStartTime', models.DateTimeField(null=True)),
                ('recipeTotalTray', models.PositiveIntegerField(null=True)),
                ('recipeTotalTrolley', models.PositiveIntegerField(null=True)),
                ('recipeBeltNo', models.PositiveIntegerField(null=True)),
                ('recipeGap', models.DurationField(null=True)),
                ('isDraft', models.BooleanField(null=True)),
                ('jobOrder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='joborders.joborder')),
            ],
        ),
        migrations.CreateModel(
            name='ProductMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productId', models.CharField(max_length=50, null=True, unique=True)),
                ('productName', models.CharField(max_length=100, null=True)),
                ('productSalesOrder', models.PositiveIntegerField(null=True)),
                ('currency', models.CharField(max_length=3, null=True)),
                ('productPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('client', models.CharField(max_length=100, null=True)),
                ('colorSet', models.CharField(max_length=100, null=True)),
                ('productExpDate', models.DateField(null=True)),
                ('productSaleDate', models.DateField(null=True)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('noOfSlices', models.PositiveIntegerField(null=True)),
                ('thickness', models.PositiveIntegerField(null=True)),
                ('tray', models.PositiveIntegerField(null=True)),
                ('trolley', models.PositiveIntegerField(null=True)),
                ('productRemarks', models.TextField(blank=True, null=True)),
                ('recipe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='joborders.recipemapping')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cutOffTime', models.DateTimeField(null=True)),
                ('spongeStart', models.DateTimeField(null=True)),
                ('spongeEnd', models.DateTimeField(null=True)),
                ('doughStart', models.DateTimeField(null=True)),
                ('doughEnd', models.DateTimeField(null=True)),
                ('firstLoafPacked', models.DateTimeField(null=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_recipe', to='joborders.recipemapping')),
            ],
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revisionId', models.CharField(blank=True, max_length=100, null=True)),
                ('dateTime', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('revision', models.CharField(blank=True, max_length=255, null=True)),
                ('ammended', models.BooleanField(default=False)),
                ('jobOrder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='joborders.joborder')),
                ('userId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
