# Generated by Django 4.2.6 on 2023-10-11 02:52

import datetime
from django.db import migrations, models
import django.db.models.deletion
import joborders.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_user_username_alter_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productId', models.CharField(max_length=50)),
                ('productPrice', models.DecimalField(decimal_places=2, max_digits=5)),
                ('productSalesOrder', models.PositiveIntegerField()),
                ('productThickness', models.PositiveIntegerField()),
                ('productSlice', models.CharField(max_length=50)),
                ('productExpDate', models.DateField(blank=True, default=datetime.datetime.today, null=True)),
                ('productSaleDate', models.DateField(blank=True, default=datetime.datetime.today, null=True)),
                ('productRemarks', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipeId', models.CharField(max_length=50)),
                ('recipeSalesOrder', models.PositiveIntegerField()),
                ('recipeProdRate', models.PositiveIntegerField()),
                ('recipeBatchSize', models.PositiveIntegerField()),
                ('recipeProdDate', models.DateField(default=joborders.models.Recipe.yesterday)),
                ('recipeKwikLokColor', models.CharField(max_length=50)),
                ('recipeBatches', models.PositiveIntegerField()),
                ('recipeCycleTime', models.DurationField()),
                ('recipeWaste', models.DecimalField(decimal_places=2, default=2.0, max_digits=5)),
                ('recipeReqTime', models.DurationField()),
                ('recipeTotalTray', models.PositiveBigIntegerField()),
                ('recipeTotalTrolley', models.PositiveIntegerField()),
                ('recipeBeltNo', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revisionId', models.CharField(max_length=50)),
                ('dateTime', models.DateField(default=datetime.datetime.today)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='JobOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobOrderId', models.CharField(max_length=50)),
                ('jobOrderCreatedDate', models.DateField(default=datetime.datetime)),
                ('totalSalesOrder', models.PositiveIntegerField()),
                ('jobOrderStatus', models.CharField(max_length=50)),
                ('currentActivity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current', to='joborders.recipe')),
                ('jobOrderRevision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_revision', to='joborders.revision')),
                ('nextActivity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='next', to='joborders.recipe')),
                ('recipeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_recipe', to='joborders.recipe')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_job', to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cutOffTime', models.DateField()),
                ('spongeStart', models.DateField()),
                ('spongeEnd', models.DateField()),
                ('doughStart', models.DateField()),
                ('doughEnd', models.DateField()),
                ('firstLoafPacked', models.DateField()),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_recipe', to='joborders.recipe')),
            ],
        ),
    ]
