# Generated by Django 4.2.6 on 2023-10-11 03:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('joborders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipeProducts',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='joborders.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activity',
            name='cutOffTime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='activity',
            name='doughEnd',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='activity',
            name='doughStart',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='activity',
            name='firstLoafPacked',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='activity',
            name='spongeEnd',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='activity',
            name='spongeStart',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='joborder',
            name='jobOrderCreatedDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='product',
            name='productExpDate',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='productSaleDate',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='revision',
            name='dateTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
