# Generated by Django 4.2.6 on 2023-10-16 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('joborders', '0002_recipe_recipeproducts_alter_activity_cutofftime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipeBatchSize',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipeBatches',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipeBeltNo',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipeCycleTime',
            field=models.DurationField(null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipeKwikLokColor',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipeProdRate',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipeProducts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='joborders.product'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipeReqTime',
            field=models.DurationField(null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipeSalesOrder',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipeTotalTray',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipeTotalTrolley',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
