# Generated by Django 4.2.6 on 2023-11-29 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joborders', '0003_remove_product_productslice_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recipe',
            new_name='RecipeMapping',
        ),
    ]
