# Generated by Django 4.2.6 on 2023-11-30 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joborders', '0004_rename_recipe_recipemapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='joborder',
            name='jobOrderGap',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
