# Generated by Django 4.2.6 on 2023-11-30 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joborders', '0005_joborder_jobordergap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joborder',
            name='jobOrderGap',
        ),
        migrations.AddField(
            model_name='recipemapping',
            name='recipeGap',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
