# Generated by Django 4.2.6 on 2023-12-01 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('joborders', '0006_remove_joborder_jobordergap_recipemapping_recipegap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipemapping',
            name='recipeGap',
        ),
        migrations.CreateModel(
            name='RecipePerDay',
            fields=[
                ('id', models.CharField(editable=False, max_length=100, primary_key=True, serialize=False)),
                ('production_date', models.DateField()),
                ('gap', models.CharField(max_length=50, null=True)),
                ('jobOrder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_days', to='joborders.joborder')),
                ('recipes', models.ManyToManyField(related_name='recipe_days', to='joborders.recipemapping')),
            ],
        ),
    ]
