# Generated by Django 4.2.6 on 2023-12-04 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joborders', '0007_remove_recipemapping_recipegap_recipeperday'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecipePerDay',
        ),
    ]
