# Generated by Django 4.2.6 on 2023-12-08 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joborders', '0011_alter_recipemapping_recipespongestarttime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipemapping',
            name='recipeSpongeStartTime',
            field=models.DateTimeField(null=True),
        ),
    ]
