# Generated by Django 4.2.6 on 2023-12-11 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joborders', '0012_alter_recipemapping_recipespongestarttime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipemapping',
            name='recipeWaste',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
