# Generated by Django 4.2.6 on 2023-12-11 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joborders', '0013_alter_recipemapping_recipewaste'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipemapping',
            name='recipeTimeVar',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
