# Generated by Django 4.2.6 on 2023-12-11 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joborders', '0014_recipemapping_recipetimevar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipemapping',
            name='recipeTimeVar',
            field=models.DurationField(max_length=50, null=True),
        ),
    ]
