# Generated by Django 4.2.6 on 2023-12-12 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joborders', '0015_alter_recipemapping_recipetimevar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='cutOffTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='doughEnd',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='doughStart',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='firstLoafPacked',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='spongeEnd',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='spongeStart',
            field=models.DateTimeField(null=True),
        ),
    ]
