# Generated by Django 4.2.6 on 2023-12-26 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('joborders', '0016_alter_activity_cutofftime_alter_activity_doughend_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='revision',
            name='jobOrder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='joborders.joborder'),
        ),
        migrations.AlterField(
            model_name='revision',
            name='dateTime',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='revision',
            name='revisionId',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='revision',
            name='userId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
