# Generated by Django 4.2.6 on 2023-12-26 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joborders', '0017_revision_joborder_alter_revision_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='revision',
            name='revision',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
