# Generated by Django 4.2.6 on 2023-12-27 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joborders', '0018_revision_revision'),
    ]

    operations = [
        migrations.AddField(
            model_name='revision',
            name='ammended',
            field=models.BooleanField(default=False),
        ),
    ]
