# Generated by Django 4.2.6 on 2024-01-02 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joborders', '0019_revision_ammended'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipemapping',
            name='isDraft',
            field=models.BooleanField(null=True),
        ),
    ]
