# Generated by Django 4.2.6 on 2024-01-16 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joborders', '0020_recipemapping_isdraft'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='ProductMapping',
        ),
    ]
