# Generated by Django 4.2.6 on 2024-01-18 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joborders', '0021_rename_product_productmapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmapping',
            name='productExpDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='productmapping',
            name='productSaleDate',
            field=models.DateField(null=True),
        ),
    ]
