# Generated by Django 4.2.6 on 2024-01-03 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poCarton', models.PositiveIntegerField()),
                ('cartonFinished', models.PositiveIntegerField()),
                ('poStatus', models.CharField(max_length=50)),
                ('po_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('poClients', models.ManyToManyField(to='purchaseorder.client')),
            ],
        ),
    ]
