# Generated by Django 4.2.6 on 2024-01-03 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchaseorder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='cartonFinished',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='poCarton',
        ),
        migrations.AddField(
            model_name='client',
            name='cartonFinished',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='poCarton',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='clientName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='poClients',
            field=models.ManyToManyField(null=True, to='purchaseorder.client'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='poStatus',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
