# Generated by Django 4.2.6 on 2024-01-03 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchaseorder', '0002_remove_purchaseorder_cartonfinished_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='poClients',
            field=models.ManyToManyField(to='purchaseorder.client'),
        ),
    ]
