# Generated by Django 4.2.6 on 2023-11-29 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipeName', models.CharField(max_length=50, unique=True)),
                ('productionRate', models.CharField(max_length=50)),
                ('stdBatchSize', models.CharField(max_length=50)),
                ('cycleTimeVariable', models.DurationField()),
            ],
        ),
    ]
