# Generated by Django 4.2.6 on 2023-12-30 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='productionRate',
            field=models.PositiveIntegerField(max_length=50),
        ),
    ]
