# Generated by Django 4.2.6 on 2023-12-30 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipe_productionrate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='stdBatchSize',
            field=models.PositiveIntegerField(),
        ),
    ]
