# Generated by Django 4.2.6 on 2024-01-15 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_recipe_stdbatchsize'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productId', models.CharField(max_length=50, null=True, unique=True)),
                ('productName', models.CharField(max_length=100, null=True)),
                ('currency', models.CharField(max_length=3, null=True)),
                ('productPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('noOfSlices', models.PositiveIntegerField(null=True)),
                ('thickness', models.PositiveIntegerField(null=True)),
                ('recipe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='recipes.recipe')),
            ],
        ),
    ]
