# Generated by Django 4.2.6 on 2024-01-15 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_product_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='productId',
        ),
    ]
